# Generated by Django 4.0.3 on 2022-03-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_rating_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rate_count',
            field=models.IntegerField(default=0),
        ),
    ]
