# Generated by Django 4.0.3 on 2022-03-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_rate_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rate_count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rating',
        ),
    ]
