# Generated by Django 4.0.3 on 2022-03-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='request.address'),
        ),
    ]
